### ISSUE TITLE
Twig/Extension dependency

### ISSUE THREAD

**Issue by barthy-koeln** [ZenSide/SonataImageBundle#9]
Hello,

is it necessary to depend on version `1.0.*` of  `twig/extensions`?
The bundle is at version `1.4.1`  now, and basically all of my projects need or use something higher than `1.0.*`.

Thanks,

Barthy

**Comment by ZenSide** [comment]
Hi,

This project is not updated since 1 year and so depedencies are not. Feel free to propose a pull request I'll be please to add to the project.

Thanks,
Nicolas
